version: '3'
services:
  chnserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: chnserver:kubernetes
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .development.env
